### ISSUE TITLE
Please add cocoapods or SPM option

### ISSUE THREAD

**Issue by ConfusedVorlon** [BranchMetrics/mac-branch-deep-linking#17]
manually dragging frameworks into projects seems barbaric!

**Comment by echo-branch** [comment]
This will be supported in the next release.  It's currently on the staging branch, if you'd prefer to try it earlier.

**Comment by echo-branch** [comment]
The 1.3.0 release has shipped with cocoapods, carthage and SPM support.  Also the pre-built framework has moved to the releases page instead of in the repo history to limit growth for SPM users.
