### ISSUE TITLE
Missing BranchWillStartSessionNotification in Unity initialisation callback - No Status 200 Error

### ISSUE THREAD

**Issue by jigjeremy** [BranchMetrics/mac-branch-deep-linking#29]
I've created a bundle target of this project to use with a Unity C# project for Mac, and I'm able to call the initalisation method without issue 

`[[Branch sharedInstance] startWithConfiguration:configuration];`

But I'm not seeing the callback _BranchWillStartSessionNotification_ that the bundle has setup. The logs show a "Status 200 error" in the BNCNetworkService.m file but I can't find any docs on how to deal with this. Any help resolving would be appreciated. 

Edit: 
I've also tested a regular Mac application using the existing Framework target, and this is calling the NSNotificationCenter events correctly, but bundling this should also work. I've verified that the methods with the postNotification call are being reached and not exiting early, and they are being called on the same thread, so this should be working.

Logs below: 

> 2022-06-01 18:56:03.223 Unity[55337:354018] [branch.io] BranchMainClass.m(386) DebugSDK: Method 'delayedOpen'.
> 2022-06-01 18:56:03.226 Unity[55337:354019] [branch.io] BNCNetworkService.m(171) Debug: Network start POST https://api.branch.io/v1/open
> {
>   "app_version" : "Unity version 2021.2.9f1",
>   "branch_key" : "key_live_joQf7gfRz1vebNOoHPFGJhnhFCarsZg0",
>   "brand" : "Apple",
>   "country" : "AU",
>   "device_fingerprint_id" : "1060367553723848226",
>   "hardware_id" : "e2:59:69:4a:9c:97",
>   "hardware_id_type" : "mac_address",
>   "identity_id" : "1060367553749163545",
>   "instrumentation" : {
>     "\/v1\/open-brtt" : "406"
>   },
>   "ios_bundle_id" : "com.unity3d.UnityEditor5.x",
>   "is_hardware_id_real" : true,
>   "language" : "en",
>   "lastest_update_time" : 1643674126000,
>   "latest_install_time" : 1620823620000,
>   "local_ip" : "192.168.1.247",
>   "mac_address" : "e2:59:69:4a:9c:97",
>   "model" : "Macmini9,1",
>   "os" : "mac_OS",
>   "os_version" : "12.4.0",
>   "screen_dpi" : 72,
>   "screen_height" : 1440,
>   "screen_width" : 3440,
>   "sdk" : "mac1.3.1",
>   "update" : 1,
>   "uri_scheme" : "com.unity3d.kharma",
>   "user_agent" : "Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit\/605.1.15 (KHTML, like Gecko)"
> }.
> 2022-06-01 18:56:03.623 Unity[55337:354019] [branch.io] BNCNetworkService.m(164) Debug: Network finish operation https://api.branch.io/v1/open 0.398s. Status 200 error (null).
> {
>   "data" : "{\"+clicked_branch_link\":false,\"+is_first_session\":false}",
>   "device_fingerprint_id" : "1060367553723848226",
>   "identity_id" : "1060367553749163545",
>   "link" : "https:\/\/link.jig.space\/a\/key_live_djg3GEvgIyILP4vbobt6ynjiutiiDxvo?%24identity_id=1060367553749163545",
>   "session_id" : "1060469105222627153"
> }.

**Comment by echo-branch** [comment]
Sorry for the late response on this. The Branch Unity SDK only supports iOS and Android. There's no layer for any other platforms.
