### ISSUE TITLE
SetIdentity() is not working correctly on MacOS

### ISSUE THREAD

**Issue by amr8** [BranchMetrics/mac-branch-deep-linking#34]
### Describe the bug

The Developer Identity of events is not changed on Branch Dashboard after calling logout() / setIdentity():

<img width="1510" alt="Screen Shot 2022-12-21 at 17 23 55" src="https://user-images.githubusercontent.com/1875602/208882589-517ea2c2-8770-457a-9a69-62115d3a81ee.png">

The Developer Identity of new events still appears as (Andy) even if I already call logout() and set another identity (Chanh).
I try testing on TestBed and it has the same issue.

### Steps to reproduce

1. call logout()
2. call setIdentity() to set another identity
3. send a new event
=> the new event appears on Branch Dashboard with the old Identity.

### Expected behavior

The Developer Identity should be updated after calling logout() / setIdentity():

### SDK Version

mac1.4.0

### XCode Version

Version 14.1 (14B47b)

### OS

12.5 (21G72)

**Comment by nsingh-branch** [comment]
This was fixed in the latest release, v1.4.1.
